import { Article } from '@/types';

export const MOCK_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'How AI is Transforming Content Creation in 2025',
    content: 'Artificial intelligence has become the backbone of modern content creation. From automated copywriting to image generation, AI tools are enabling creators to produce high-quality content at unprecedented speeds. Discover how AI is revolutionizing the industry and what strategies smart creators are using to stay ahead.',
    imageUrl: '/ai-content-dashboard.png',
    mode: 'topics',
    status: 'draft',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '2',
    title: 'The Future of Web Design: AI-Powered Layouts',
    content: 'Web design is entering a new era where artificial intelligence predicts user behavior and automatically optimizes layouts. This comprehensive guide explores how machine learning algorithms are changing design workflows and improving user experiences across the web.',
    imageUrl: '/modern-web-design-interface.jpg',
    mode: 'website',
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 6 * 60 * 60 * 1000),
    platforms: ['LinkedIn', 'Twitter'],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: '3',
    title: 'Creative Image Generation Guide',
    content: 'Master the art of AI image generation with our complete guide. Learn prompt engineering techniques, understand model capabilities, and create stunning visuals for your marketing campaigns. From concept to final render, we cover everything you need to know.',
    imageUrl: '/ai-generated-art-studio.jpg',
    mode: 'image',
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    platforms: ['Facebook', 'Instagram'],
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: '4',
    title: 'Scaling Your Content Strategy with Automation',
    content: 'Learn how to scale your content production without burning out your team. This article covers automation strategies, tool integrations, and workflow optimization techniques that have helped creators increase output by 300% while maintaining quality.',
    imageUrl: '/ai-content-dashboard.png',
    mode: 'topics',
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    platforms: ['Facebook', 'Instagram'],
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
  },
  {
    id: '5',
    title: 'Building Personal Brands with AI Content',
    content: 'Your personal brand is your most valuable asset in the digital age. Learn how to leverage AI tools to consistently produce content that reflects your unique voice and values. This guide covers content calendars, platform strategies, and automation workflows tailored for personal brands.',
    imageUrl: '/modern-web-design-interface.jpg',
    mode: 'topics',
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    platforms: ['Twitter', 'LinkedIn'],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: '6',
    title: 'Prompt Engineering Mastery',
    content: 'Unlock the full potential of AI models by mastering prompt engineering. This in-depth guide teaches you the psychology behind effective prompts, advanced techniques, and real-world examples that generate superior results every time.',
    imageUrl: '/ai-generated-art-studio.jpg',
    mode: 'website',
    status: 'scheduled',
    scheduledAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    platforms: ['LinkedIn'],
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: '7',
    title: 'The Economics of AI-Powered Content',
    content: 'Discover how AI content generation affects ROI and business metrics. This article breaks down cost analysis, productivity gains, and quality improvements when switching to AI-assisted workflows. Perfect for business leaders considering the investment.',
    imageUrl: '/ai-content-dashboard.png',
    mode: 'topics',
    status: 'published',
    platforms: ['Facebook', 'LinkedIn'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: '8',
    title: 'Top 10 AI Tools for Content Creators in 2024',
    content: 'We reviewed and ranked the best AI tools available for content creators. From writing assistants to image generators and video editors, discover which tools offer the best value and performance for your specific needs.',
    imageUrl: '/ai-generated-art-studio.jpg',
    mode: 'topics',
    status: 'published',
    platforms: ['Twitter', 'Facebook', 'LinkedIn'],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: '9',
    title: 'How to Stay Authentic While Using AI',
    content: 'Using AI tools doesn\'t mean losing your authentic voice. Learn best practices for maintaining brand authenticity while leveraging AI for efficiency. Real examples show how successful creators balance automation with personalization.',
    imageUrl: '/modern-web-design-interface.jpg',
    mode: 'website',
    status: 'published',
    platforms: ['LinkedIn'],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: '10',
    title: 'Email Marketing Evolution: AI Integration',
    content: 'Email marketing is being revolutionized by AI-powered personalization and automation. This comprehensive guide shows how to implement AI in your email campaigns for better open rates, click-through rates, and conversions.',
    imageUrl: '/ai-content-dashboard.png',
    mode: 'topics',
    status: 'published',
    platforms: ['LinkedIn', 'Twitter'],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: '11',
    title: 'Social Media Strategy with AI Analytics',
    content: 'Leverage AI-powered analytics to understand your audience better and optimize your social strategy. Discover which content performs best, when to post, and how to maximize engagement across all platforms.',
    imageUrl: '/ai-content-dashboard.png',
    mode: 'website',
    status: 'published',
    platforms: ['Instagram', 'Facebook'],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: '12',
    title: 'From Idea to Publication: A 7-Day Framework',
    content: 'Develop a repeatable framework for generating and publishing high-quality content in just 7 days. This proven system has helped dozens of creators maintain consistent output without sacrificing quality.',
    imageUrl: '/modern-web-design-interface.jpg',
    mode: 'topics',
    status: 'published',
    platforms: ['LinkedIn', 'Twitter', 'Facebook'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: '13',
    title: 'Visual Storytelling: Creating Engaging Graphics',
    content: 'Master the art of visual storytelling and create graphics that capture attention. Learn design principles, color theory, and composition techniques that make your visual content stand out across social media platforms.',
    imageUrl: '/ai-generated-art-studio.jpg',
    mode: 'image',
    status: 'published',
    platforms: ['Instagram', 'Pinterest'],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: '14',
    title: 'Content Repurposing: Maximizing Content ROI',
    content: 'Learn how to repurpose your content across multiple platforms and formats. This guide shows strategic approaches to turn one piece of content into dozens of variations, multiplying your reach and engagement.',
    imageUrl: '/modern-web-design-interface.jpg',
    mode: 'topics',
    status: 'published',
    platforms: ['Twitter', 'LinkedIn'],
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
  },
  {
    id: '15',
    title: 'Data-Driven Content: Using Analytics to Improve',
    content: 'Transform raw analytics data into actionable insights for your content strategy. Discover which metrics matter most and how to use them to continuously improve your content performance.',
    imageUrl: '/ai-content-dashboard.png',
    mode: 'website',
    status: 'published',
    platforms: ['LinkedIn'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
];
